import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import AppHeader from "./components/app-header"; // This import should remain commented out or removed
import { AppFooter } from "./components/app-footer";
import { SnackbarProvider } from "notistack"; // Note: SnackbarProvider is typically used with a client context provider
import { Toaster } from "sonner";
import { ClerkProvider, SignInButton, SignUpButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Toaster position="top-right" richColors />
         
          {children}
          <AppFooter />
        </body>
      </html>
    </ClerkProvider>
  );
}
